# Standard Flutter Podfile
platform :ios, '15.0'

# Pointer to Flutter's native podhelper
require_relative 'Flutter/podhelper'

target 'Runner' do
  # linkage => :static is the only way to avoid Firebase Duplicate Symbol errors
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Unified iOS 15.0 for all dependencies
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Resolve modular header conflicts
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
